name: weewx_pwa
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  expandable_page_view: ^1.0.17
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
