name: weewx_now_app
description: A mobile app "skin" for WeeWX weather server
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  dio: ^5.4.0
  go_router: ^13.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  flutter_platform_widgets: ^6.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true #intl

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"

  ios: false
  # image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
