name: weewx_now_app
description: A mobile app as "skin" for WeeWX weather server
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  dio: ^5.4.0
  go_router: ^13.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  flutter_platform_widgets: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/