name: weewx_pwa
description: A progressive web app as "skin" for WeeWX weather server
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  get_it: ^7.6.4
  dio: ^5.4.0
  go_router: ^12.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/